### ISSUE TITLE
Extending functionality

### ISSUE THREAD

**Issue by noplanman** [nykma/otp#1]
Hi @nykma 

I've been using this script for quite some time and have updated it quite a bit on my fork.

I see that you no longer develop it actively, so I was wondering if it was ok with you if I continued development on my branch and looked into packaging it for brew, making my fork the "official" version of the script.

Is that ok for you?

**Comment by nykma** [comment]
Hi @noplanman 
Wow, I can't believe there IS someone using my little script!
Of course I'm willing to change the 'official' repo to yours. I'll change my repo discription later. Thank you for the maintenance!

**Comment by noplanman** [comment]
>  Wow, I can't believe there IS someone using my little script!

This script is amazing! Couldn't live without it any more 👍 
Do you use it for yourself? If so, check out my additions, you'll probably like them!

I'll look into releasing it to Homebrew then 😃 
And also look into HOTP.

**Comment by nykma** [comment]
Yeah I've checked your modification. IT'S AWESOME!
